# Analysis of Healthcare System of California
CREATE DATABASE Healthcare;
USE Healthcare;
SELECT * FROM healthcare.health;

--- 1. TOTAL DISCHARGE
SELECT SUM(DIS_TOT) FROM health;

--- 2.AVERAGE PATIENT DAYS
SELECT ROUND(AVG(DAY_TOT),0) AS DAY_AVG,TYPE_HOSP FROM health
GROUP BY TYPE_HOSP ;

--- 3.NET REVENUE
SELECT SUM(NET_TOT) FROM health;

--- 4.AVAILABLE BEDS EACH TYPE OF HOSPITAL
SELECT TYPE_HOSP,SUM(AVL_BEDS) AS TOTAL_BEDS FROM health
GROUP BY TYPE_HOSP;

--- 5.TOP 10 COUNTYS BY REVENUE
SELECT COUNTY_NAME,SUM(NET_TOT) AS TOTAL_REVENUE FROM health
GROUP BY COUNTY_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

--- 6.TOTAL HOSPITAL
SELECT DISTINCT(COUNT(FAC_NO)) AS TOT_HOS FROM health;

--- 7.TYPE OF HOSPITAL REVENUE
SELECT TYPE_HOSP,SUM(NET_TOT) AS TOT_REVENUE FROM health
GROUP BY TYPE_HOSP
ORDER BY TOT_REVENUE DESC ;

---- 8.TOTAL PATIENTS
select SUM(GRIP_TOT) + SUM( GROP_TOT) AS TOT_PATIENT FROM HEALTH;

--- 9.COUNTY WISE HOSPITAL
select COUNTY_NAME, count(distinct FAC_NO) AS TOTAL_HOS FROM HEALTH group by COUNTY_NAME order by TOTAL_HOS DESC;


--- KPI-10
SELECT 
YEAR(STR_TO_DATE(CONVERT(BEG_DATE, CHAR), '%d-%m-%Y')) AS YEAR_ONLY,
 sum(NET_MCAR), sum(NET_MCAR_MC),sum(NET_MCAL), sum(NET_MCAL_MC),sum(NET_CNTY), sum(NET_CNTY_MC),sum(NET_THRD), sum(NET_THRD_MC),sum(NET_INDGNT)
 FROM HEALTH 
 GROUP BY     YEAR(STR_TO_DATE(CONVERT(BEG_DATE, CHAR), '%d-%m-%Y'));
 
--- KPI-11 
SELECT  sum(NET_TOT),TYPE_CNTRL
FROM HEALTH
GROUP BY TYPE_CNTRL 
ORDER BY  SUM(NET_TOT) DESC LIMIT 5;
 
 
 
 
 







